---
name: Jazzy build_test

on:
  workflow_dispatch:

  push:
    branches:
      - jazzy
  
  pull_request:
    branches:
      - jazzy

jobs:
  test_build_jazzy:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-core
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          skip-tests: false
          rosdep-check: true
          package-name: 'dual_laser_merger'
